apiVersion: apps/v1
kind: DaemonSet # 파스칼 케이스로 작성
metadata:
  name: monitoring-daemon
spec:
  template:
    metadata:
      labels:
        app: monitoring-agent
    spec:
      containers:
      - name: monitoring-agent
        image: nginx
  selector:
    matchLabels:
      app: monitoring-agent
